### PR TITLE
[Feat] Add Chinese-friendly optimizations to Dockerfile

### PR DESCRIPTION
**Pull request by CornWorld**

### CODE REVIEW

**Comment by g-plane** [comment]
Creating a new Dockerfile isn't preferred. What about allowing to override by using environment variables?

**Comment by CornWorld** [comment]
maybe you are right, but this allows new user discover that easily

**Comment by g-plane** [comment]
You can document this feature instead of hard-coding text. Actually, they can switch any mirrors as they want.

**Comment by CornWorld** [comment]
Yeah, it seems you are right.
I'll make it soon.

**Comment by mochaaP** [comment]
You can build the image on a non-firewalled machine and import that to your deployment target. Moreover, this Dockerfile is for development usage (as it uses SQLite and Apache), it's not recommended to deploy this in production. I'd like to close this.

**Pull request closed without merging**
